# @format

env:
  browser: true
  es2020: true
extends:
  - "eslint:recommended"
  - "airbnb"
  - "airbnb-typescript"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react-hooks/recommended"
  - "prettier"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: "latest"
  sourceType: "module"
  project: "./tsconfig.json"
ignorePatterns:
  - "vite.config.ts"
plugins:
  - "react-refresh"
rules:
  "react-refresh/only-export-components": "warn"
  "react/jsx-uses-react": "off"
  "react/react-in-jsx-scope": "off"
  "import/extensions":
    - "warn"
    - "ignorePackages"
